-- =============================================================================
-- 82_deduplicar_recordatorios.sql
-- Una entrega persistente por persona, quiniela, partido y tipo de aviso.
-- NO envía nada al aplicarse: crea la bitácora y la reclamación atómica que
-- usa el backend. Idempotente.
-- =============================================================================
--
-- APLICADA EN PRODUCCIÓN el 21 sep 2026 por el agente, con autorización
-- explícita del dueño. Verificada leyendo la base, no por el «ok» del editor:
-- clave única (user_id, league_id, match_id, tipo), RLS activa y SIN políticas,
-- ni la tabla ni la RPC ni la secuencia alcanzables por anon/authenticated, y
-- EXECUTE solo para service_role. Los dos guardas de la RPC (jsonb que no es
-- arreglo, tipo vacío) se probaron a la contra: rechazan.
--
-- La ventana [45, 60) evita solapamientos solo cuando el cron corre con la
-- cadencia ideal. Un reintento manual, dos peticiones concurrentes o un atraso
-- desigual pueden seleccionar el mismo partido. La barrera tiene que estar en
-- Postgres ANTES del push: un flag en memoria no coordina dos procesos.
--
-- SEMÁNTICA ANTE FALLOS. Una entrega nace `claimed`. Si ningún dispositivo la
-- recibe, el backend la marca `failed`; el siguiente cron puede reclamarla.
-- Si el proceso muere sin cerrarla, vence a los 5 minutos y también se puede
-- reclamar. Si Web Push aceptó el mensaje pero el proceso murió antes de
-- marcarlo `delivered`, un reintento podría repetirlo: Web Push no ofrece una
-- clave de idempotencia. Se elige al-menos-una-vez antes que perder el aviso.


CREATE TABLE IF NOT EXISTS public.notification_deliveries (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  league_id     uuid NOT NULL REFERENCES public.leagues(id) ON DELETE CASCADE,
  match_id      integer NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  tipo          text NOT NULL CHECK (length(tipo) BETWEEN 1 AND 80),
  status        text NOT NULL DEFAULT 'claimed'
                CHECK (status IN ('claimed', 'delivered', 'failed')),
  attempts      integer NOT NULL DEFAULT 1 CHECK (attempts >= 1),
  claim_token   uuid NOT NULL,
  claimed_at    timestamptz NOT NULL DEFAULT now(),
  delivered_at  timestamptz,
  last_error    text CHECK (last_error IS NULL OR length(last_error) <= 120),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_deliveries_unique
    UNIQUE (user_id, league_id, match_id, tipo),
  CONSTRAINT notification_deliveries_delivered_consistent
    CHECK ((status = 'delivered') = (delivered_at IS NOT NULL))
);

COMMENT ON TABLE public.notification_deliveries IS
  'Bitácora y deduplicación de avisos push. Solo la usa el backend con service_role.';
COMMENT ON COLUMN public.notification_deliveries.last_error IS
  'Categoría cerrada; nunca mensaje crudo del proveedor ni datos del dispositivo.';

CREATE INDEX IF NOT EXISTS notification_deliveries_retry_idx
  ON public.notification_deliveries (tipo, status, claimed_at)
  WHERE status IN ('claimed', 'failed');

ALTER TABLE public.notification_deliveries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.notification_deliveries FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.notification_deliveries TO service_role;

DO $secuencia$
DECLARE v_secuencia regclass;

BEGIN;

CREATE TABLE IF NOT EXISTS public.notification_deliveries (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  league_id     uuid NOT NULL REFERENCES public.leagues(id) ON DELETE CASCADE,
  match_id      integer NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  tipo          text NOT NULL CHECK (length(tipo) BETWEEN 1 AND 80),
  status        text NOT NULL DEFAULT 'claimed'
                CHECK (status IN ('claimed', 'delivered', 'failed')),
  attempts      integer NOT NULL DEFAULT 1 CHECK (attempts >= 1),
  claim_token   uuid NOT NULL,
  claimed_at    timestamptz NOT NULL DEFAULT now(),
  delivered_at  timestamptz,
  last_error    text CHECK (last_error IS NULL OR length(last_error) <= 120),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_deliveries_unique
    UNIQUE (user_id, league_id, match_id, tipo),
  CONSTRAINT notification_deliveries_delivered_consistent
    CHECK ((status = 'delivered') = (delivered_at IS NOT NULL))
);

COMMENT ON TABLE public.notification_deliveries IS
  'Bitácora y deduplicación de avisos push. Solo la usa el backend con service_role.';
COMMENT ON COLUMN public.notification_deliveries.last_error IS
  'Categoría cerrada; nunca mensaje crudo del proveedor ni datos del dispositivo.';

CREATE INDEX IF NOT EXISTS notification_deliveries_retry_idx
  ON public.notification_deliveries (tipo, status, claimed_at)
  WHERE status IN ('claimed', 'failed');

ALTER TABLE public.notification_deliveries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.notification_deliveries FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.notification_deliveries TO service_role;

DO $secuencia$
DECLARE v_secuencia regclass;
BEGIN
  SELECT pg_get_serial_sequence('public.notification_deliveries', 'id')::regclass
    INTO v_secuencia;
  IF v_secuencia IS NOT NULL THEN
    EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM PUBLIC, anon, authenticated', v_secuencia);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', v_secuencia);
  END IF;
END $secuencia$;

CREATE OR REPLACE FUNCTION public.claim_notification_deliveries(
  p_entregas jsonb,
  p_tipo text
)
RETURNS TABLE (
  claimed_user_id uuid,
  claimed_league_id uuid,
  claimed_match_id integer,
  claimed_token uuid
)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path TO public
AS $func$
BEGIN
  IF NOT public.es_backend() THEN
    RAISE EXCEPTION 'Solo el backend puede reclamar notificaciones';
  END IF;
  IF p_tipo IS NULL OR length(p_tipo) NOT BETWEEN 1 AND 80 THEN
    RAISE EXCEPTION 'Tipo de notificación inválido';
  END IF;
  IF jsonb_typeof(p_entregas) IS DISTINCT FROM 'array'
     OR jsonb_array_length(p_entregas) > 1000 THEN
    RAISE EXCEPTION 'El lote de entregas debe ser un arreglo de hasta 1000 filas';
  END IF;

  RETURN QUERY
  WITH incoming AS (
    SELECT DISTINCT e.user_id, e.league_id, e.match_id, e.claim_token
    FROM jsonb_to_recordset(p_entregas) AS e(
      user_id uuid, league_id uuid, match_id integer, claim_token uuid)
    JOIN public.league_members lm
      ON lm.user_id = e.user_id AND lm.league_id = e.league_id
    JOIN public.leagues l ON l.id = e.league_id
    JOIN public.matches m
      ON m.id = e.match_id AND m.tournament_id = l.tournament_id
    WHERE e.claim_token IS NOT NULL
      AND m.status NOT IN ('finished', 'cancelled', 'postponed')
      AND m.kickoff_at - interval '15 minutes' > now()
      AND NOT EXISTS (
        SELECT 1 FROM public.predictions p
        WHERE p.user_id = e.user_id
          AND p.league_id = e.league_id
          AND p.match_id = e.match_id)
  ), retried AS (
    UPDATE public.notification_deliveries nd
       SET status = 'claimed',
           attempts = nd.attempts + 1,
           claim_token = i.claim_token,
           claimed_at = now(),
           delivered_at = NULL,
           updated_at = now()
      FROM incoming i
     WHERE nd.user_id = i.user_id
       AND nd.league_id = i.league_id
       AND nd.match_id = i.match_id
       AND nd.tipo = p_tipo
       AND (nd.status = 'failed'
         OR (nd.status = 'claimed'
             AND nd.claimed_at < now() - interval '5 minutes'))
    RETURNING nd.user_id, nd.league_id, nd.match_id, nd.claim_token
  )
  SELECT r.user_id, r.league_id, r.match_id, r.claim_token FROM retried r;

  RETURN QUERY
  WITH incoming AS (
    SELECT DISTINCT e.user_id, e.league_id, e.match_id, e.claim_token
    FROM jsonb_to_recordset(p_entregas) AS e(
      user_id uuid, league_id uuid, match_id integer, claim_token uuid)
    JOIN public.league_members lm
      ON lm.user_id = e.user_id AND lm.league_id = e.league_id
    JOIN public.leagues l ON l.id = e.league_id
    JOIN public.matches m
      ON m.id = e.match_id AND m.tournament_id = l.tournament_id
    WHERE e.claim_token IS NOT NULL
      AND m.status NOT IN ('finished', 'cancelled', 'postponed')
      AND m.kickoff_at - interval '15 minutes' > now()
      AND NOT EXISTS (
        SELECT 1 FROM public.predictions p
        WHERE p.user_id = e.user_id
          AND p.league_id = e.league_id
          AND p.match_id = e.match_id)
  ), inserted AS (
    INSERT INTO public.notification_deliveries (
      user_id, league_id, match_id, tipo, status, attempts, claim_token,
      claimed_at, delivered_at, last_error, created_at, updated_at)
    SELECT i.user_id, i.league_id, i.match_id, p_tipo, 'claimed', 1,
           i.claim_token, now(), NULL, NULL, now(), now()
    FROM incoming i
    ON CONFLICT ON CONSTRAINT notification_deliveries_unique DO NOTHING
    RETURNING user_id, league_id, match_id, claim_token
  )
  SELECT i.user_id, i.league_id, i.match_id, i.claim_token FROM inserted i;
END;
$func$;

COMMENT ON FUNCTION public.claim_notification_deliveries(jsonb, text) IS
  'Interna del backend: reclama atómicamente avisos nuevos, fallidos o abandonados.';

REVOKE ALL ON FUNCTION public.claim_notification_deliveries(jsonb, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_notification_deliveries(jsonb, text)
  TO service_role;

DO $verificar$
DECLARE v_columnas text[];
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'notification_deliveries'
      AND c.relrowsecurity) THEN
    RAISE EXCEPTION 'notification_deliveries no quedó con RLS';
  END IF;

  SELECT array_agg(a.attname::text ORDER BY u.ord) INTO v_columnas
  FROM pg_constraint c
  JOIN LATERAL unnest(c.conkey) WITH ORDINALITY u(attnum, ord) ON true
  JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = u.attnum
  WHERE c.conrelid = 'public.notification_deliveries'::regclass
    AND c.conname = 'notification_deliveries_unique';
  IF v_columnas IS DISTINCT FROM ARRAY['user_id','league_id','match_id','tipo'] THEN
    RAISE EXCEPTION 'La clave de deduplicación quedó incorrecta: %', v_columnas;
  END IF;

  IF has_table_privilege('anon', 'public.notification_deliveries', 'SELECT')
     OR has_table_privilege('anon', 'public.notification_deliveries', 'INSERT')
     OR has_table_privilege('authenticated', 'public.notification_deliveries', 'SELECT')
     OR has_table_privilege('authenticated', 'public.notification_deliveries', 'INSERT')
     OR has_function_privilege('anon',
          'public.claim_notification_deliveries(jsonb,text)', 'EXECUTE')
     OR has_function_privilege('authenticated',
          'public.claim_notification_deliveries(jsonb,text)', 'EXECUTE') THEN
    RAISE EXCEPTION 'La bitácora o su RPC quedaron alcanzables desde el cliente';
  END IF;
  IF NOT has_function_privilege('service_role',
           'public.claim_notification_deliveries(jsonb,text)', 'EXECUTE') THEN
    RAISE EXCEPTION 'service_role no puede reclamar notificaciones';
  END IF;
  IF pg_get_functiondef(
       'public.claim_notification_deliveries(jsonb,text)'::regprocedure)
       NOT ILIKE '%ON CONFLICT ON CONSTRAINT notification_deliveries_unique DO NOTHING%' THEN
    RAISE EXCEPTION 'La reclamación nueva dejó de usar ON CONFLICT DO NOTHING';
  END IF;

  RAISE NOTICE 'Recordatorios: clave única, reclamación atómica y reintentos listos.';
END $verificar$;

NOTIFY pgrst, 'reload schema';
COMMIT;
